version: "3.3"

secrets:
  pihole-webpassword:
    file: ./secrets/pihole-webpassword
  ssl-cert:
    file: ./secrets/ssl-cert
  ssl-key:
    file: ./secrets/ssl-key

services:
  tailscale:
    container_name: tailscale
    image: docker.io/tailscale/tailscale:latest
    environment:
      TS_ACCEPT_DNS: 1
      TS_HOSTNAME: atlas
      TS_ROUTES: 10.0.0.0/24
      TS_USERSPACE: 1
      TS_EXTRA_ARGS: --advertise-exit-node
      TS_AUTH_ONCE: 1
    env_file:
      - ./secrets/tailscale-authkey.env
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale/state:/var/lib/tailscale
    network_mode: host
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Europe/Athens
      WEBPASSWORD_FILE: /run/secrets/pihole-webpassword
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    secrets:
      - pihole-webpassword
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE
      - CAP_CHOWN
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: docker.io/nginx:latest
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/logs
      - ./nginx/ssl:/ssl:ro
      - ./nginx/www:/www:ro
    secrets:
      - ssl-cert
      - ssl-key
    restart: unless-stopped
