version: "3.3"

services:
  tailscale:
    container_name: tailscale
    image: docker.io/tailscale/tailscale:latest
    env_file:
      - ./tailscale/config.env
      - ./secrets/tailscale-authkey.env
    environment:
      TS_STATE_DIR: /tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale/state:/tailscale
    network_mode: host
    restart: unless-stopped

  samba:
    container_name: samba
    build:
      context: ./samba
    environment:
      USERS_FILE: /run/secrets/samba-users
    ports:
      - 135:135
      - 445:445
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - ./samba/shares:/shares
      - ./secrets/samba-users:/asd
    secrets:
      - samba-users
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    networks:
      - front
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      WEBPASSWORD_FILE: /run/secrets/pihole-webpassword
    env_file:
      - ./pihole/config.env
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    secrets:
      - pihole-webpassword
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE
      - CAP_CHOWN
    restart: unless-stopped

  syncthing:
    container_name: syncthing
    image: docker.io/syncthing/syncthing
    hostname: atlas
    networks:
      - front
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    env_file:
      - ./syncthing/config.env
    volumes:
      - ./syncthing/sync:/var/syncthing
    restart: unless-stopped

  nginx:
    container_name: nginx
    depends_on:
      - pihole
      - syncthing
    image: docker.io/nginx:latest
    networks:
      - front
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/logs
      - ./nginx/ssl:/ssl:ro
      - ./nginx/www:/www:ro
    secrets:
      - ssl-cert
      - ssl-key
    restart: unless-stopped

networks:
  front:

secrets:
  pihole-webpassword:
    file: ./secrets/pihole-webpassword
  ssl-cert:
    file: ./secrets/ssl-cert
  ssl-key:
    file: ./secrets/ssl-key
  samba-users:
    file: ./secrets/samba-users
