#!/usr/bin/env bash
set -eu

LABROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$LABROOT"

SERVICES=(
  tailscale
  nginx
  syncthing
  pihole
  vaultwarden
)

function pushd {
  command pushd "$@" >/dev/null
}

function popd {
  command popd "$@" >/dev/null
}

function die {
  echo "[*] $@"
  exit 1
}

function run_service_hook {
  local service="${1:?expected service}"
  local hook="${2:?expected hook}"
  shift 2

  pushd "./$service"
  if [ -f ./service ]; then
    env \
      LABROOT="$LABROOT" \
      SECRETS_DIR="$LABROOT/secrets" \
      SERVICE="$service" \
      ./service "$hook" "$@"
  fi
  popd
}

function do_install_single {
  local service="$1"

  if [ ! -f "./units/$service.container" ]; then
    echo "service not found"
    return 1
  fi

  ln -vrs "./units/$service.container" /etc/containers/systemd
  run_service_hook "$service" install
}

function cmd_install {
  local all="${1+x}"

  if [ -z "$all" ]; then
    for service in "${SERVICES[@]}"; do
      do_install_single "$service"
    done
  else
    while [ ! -z "${1+x}" ]; do
      do_install_single "$1"
      shift
    done
  fi
}

function main {
  local cmd="${1:?expected command}"
  shift

  case "$cmd" in
    "install") cmd_install "$@";;
    *) die "unknown command";;
  esac
}

main "$@"
