#!/usr/bin/env bash
set -eu

function service_install {
  mkdir -p data
  ln -rsf backup.cron /etc/cron.d/vaultwarden-backup
}

function main {
  local hook="${1:?}"
  shift

  case "$hook" in
    "install") service_install "$@";;
    *) ;;
  esac
}

main "$@"
