#!/usr/bin/env bash
set -eu

function service_install {
  mkdir -p etc-pihole
  mkdir -p etc-dnsmasq.d

  podman secret create pihole-webpassword "$SECRETS_DIR/pihole-webpassword"
}

function main {
  local hook="${1:?}"
  shift

  case "$hook" in
    "install") service_install "$@";;
    *) ;;
  esac
}

main "$@"
