#!/usr/bin/env bash

function service_install {
  mkdir -p logs
}

function main {
  local hook="${1:?}"
  shift

  case "$hook" in
    "install") service_install "$@";;
    *) ;;
  esac
}

main "$@"
