#!/usr/bin/env bash
set -eu

function service_install {
  mkdir -p logs

  podman secret create ssl-cert "$SECRETS_DIR/ssl-cert"
  podman secret create ssl-key "$SECRETS_DIR/ssl-key"
}

function main {
  local hook="${1:?}"
  shift

  case "$hook" in
    "install") service_install "$@";;
    *) ;;
  esac
}

main "$@"
