server:
  disable: true

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /promtail/positions.yaml

scrape_configs:
  - job_name: syslog

    journal:
      labels:
        job: "syslog"

    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"

    relabel_configs:
      - source_labels: [__journal__hostname, __syslog_message_hostname]
        target_label: hostname
      - source_labels: [__journal_priority_keyword, __syslog_message_severity]
        target_label: level
      - source_labels: [__journal__systemd_unit, __journal__systemd_user_unit, __syslog_message_app_name]
        target_label: application
      - source_labels: [__syslog_message_facility]
        target_label: facility
      - source_labels: [__syslog_connection_hostname]
        target_label: connection_hostname

  - job_name: nginx

    static_configs:
      - targets:
          - localhost

        labels:
          job: "nginx"
          __path__: /nginx-logs/*
